name: build-lib

on:
  pull_request:
    branches:
      - main
    paths:
      - src/lib/**
      - .github/workflows/build-lib.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:lib
