name: build-userscript

env:
  SEMVER: 0.0.${{ github.run_number }}-build-userscript

on:
  pull_request:
    branches:
      - main
    paths:
      - src/apps/userscript/**
      - .github/workflows/build-userscript.yml
      - .tool-versions
      - eslint.config.mjs
      - package*
      - tsconfig.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:userscript

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          path: dist/userscript/playlister.user.js
