name: release

env:
  SEMVER: 0.0.${{ github.run_number }}

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build Userscript
        run: npm run package:userscript

      - name: Release
        run: gh release create v${{ env.SEMVER }} --generate-notes dist/userscript/playlister.user.js
        env:
          GH_TOKEN: ${{ github.token }}
